module.exports = {
  USER_ADMIN: "ADMIN",
  USER_STAFF: "STAFF",
  RM_CATEGORY: "RM_CATEGORY",
  ROOM_STATUS_VACANT: "VACANT",
  ROOM_STATUS_OCCUPIED: "OCCUPIED",
  ROOM_STATUS_VACANT_DIRTY: "VACANT DIRTY",
  ROOM_STATUS_EXPECTED: "EXPECTED",
  ROOM_STATUS_OUT_OF_ORDER: "OUT_OF_ORDER",
  CHARGE_TYPE_ROOM_CHARGE: "ROOM CHARGE",
  CHARGE_TYPE_ROOM_DISCOUNT: "ROOM DISCOUNT",
  CHARGE_TYPE_ROOM_CHARGE_PAYMENT: "ROOM CHARGE PAYMENT"
};
